# Generated by Django 4.2.7 on 2023-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='idk', upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
